# Generated by Django 2.1.7 on 2019-05-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=30)),
                ('uploaded_file', models.FileField(upload_to='document_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
